<a href="https://colab.research.google.com/github/efwoods/tf-cert/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tesnors & NumPy
* Using @tf.function (a way to speed up your regular Pythong functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

## Introduction to Tensors

### Setup

In [316]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


### Scalars

In [317]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [318]:
# Check the number of dimension of a tensor (ndim stand for number of dimensions)
scalar.ndim

0

### Vectors

In [319]:
# Create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [320]:
# Check the dimension of our vector
vector.ndim

1

### Matrices

In [321]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [322]:
matrix.ndim

2

In [323]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16) # specify the datatype with the dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [324]:
# What's the number of dimensions of another matrix?
another_matrix.ndim

2

### Tensors

In [325]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3, ], [4,5,6], ], [[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [326]:
tensor.ndim

3

### Summary

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Video 17: Creating tensors with `tf.Variable` & modifying tensor values

### Changeable and Unchangeable Tensors 

In [327]:
# Create the same tensor with tf.Variabl() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [328]:
# Let's try to change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7)

## Video 18: Creating Random Tensors


### Creating Random Tensors

Random tensors are tensors of some arbitrary size filled with random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor: when you want to shuffle your data so the inherent data doesn't effect learning
not_shuffled = tf.constant([[10, 7], [3,4],[2,5]])
# not_shuffled.ndim


# shuffle the non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# shuffle the non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
not_shuffled

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


If you want the shuffled tensors to be in the same order, the global and operational random seeds must be the same.
> [Rule 4](https://www.tensorflow.org/api_docs/python/tf/random/set_seed): "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Exercise
🛠 ** Exercise: ** Read through TensorFlow Documentation on [random seed generation](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)
and practice writing 5 random tensors and shuffle them.

#### Test 1: Will using the same seed to generate and shuffle result in distinct tensors? 


In [ ]:
# Create Tensor
tensor_1_not_shuffled = tf.random.Generator.from_seed(42)
tensor_1_not_shuffled = tensor_1_not_shuffled.normal(shape=(3,2))
tensor_1_not_shuffled


In [ ]:
# Shuffle tensor
tf.random.shuffle(tensor_1_not_shuffled)

# result: will shuffle vectors every time

In [ ]:
tf.random.set_seed(42) # Global level random seed
tensor_1_shuffled = tf.random.shuffle(tensor_1_not_shuffled, seed=42) # operational level random seed
tensor_1_shuffled

# always the same tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tensor_1_shuffled == tensor_1_not_shuffled

#### Test 1 Results: 
Using the same seed to shuffle tensors and generate tensors will result in the same tensor. Shuffling the tensor without setting the seed will rearrange the vectors in the tensor which will result in two distinct tensors that are distinguished by order of the vectors. The vectors contain the same elements.

#### Test 2
Does changing the seed of the shuffle change the resulting tensor if the tensors were generated from the same seed?

In [ ]:
# Test 2
tensor_2_not_shuffled = tf.random.Generator.from_seed(42)
tensor_2_not_shuffled = tensor_2_not_shuffled.normal(shape=(3,2))
tensor_2_not_shuffled


In [ ]:
# Shuffle tensor
tf.random.shuffle(tensor_2_not_shuffled)


# result: will shuffle vectors every time

In [ ]:
tf.random.set_seed(7)
tensor_2_shuffled = tf.random.shuffle(tensor_2_not_shuffled, seed=7)
tensor_2_shuffled

In [ ]:
# Are the tensors different?
tensor_1_shuffled == tensor_2_shuffled



#### Test 2 Results
Although the tensors were both created with the same seed, once the tensors were shuffled with different seeds, the tensors became distinct.

### Summary

## Video 19: Creating Tensors from Numpy Arrays 

### Other ways to make tensors ( ones and zeros)

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The difference between NumPy arrays and tensors is that tensors can be run much faster on a GPU

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# Convert a numpy array into a tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# Change the shape of a tensor
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
# The dimensions in the shape must multiply to equal the number of elements in the numpy array
number_of_elements_in_the_numpy_array = numpy_A.shape
B_dimension = B.get_shape()

product_of_dimensions = B_dimension[0] * B_dimension[1] * B_dimension[2]

numpy_A.shape, B_dimension, product_of_dimensions, number_of_elements_in_the_numpy_array[0], product_of_dimensions == number_of_elements_in_the_numpy_array[0]


((24,), TensorShape([2, 3, 4]), 24, 24, True)

## Video 20: Getting more information from tensors (tensor attributes)

### Getting information from tensors

Tensor Attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [352]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

##### Shape
- Meaning: The length (number of elements) of each of the dimensions of a tensor.
- Code: tensor.shape

In [336]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

##### Rank
- Meaning: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
- Code: tensor.ndim

In [335]:
rank_4_tensor.ndim

4

##### Axis or dimension
- Meaning: A particular dimension of a tensor.
- Code: tensor[0], tensor[:,1]...

In [338]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [342]:
# rank_4_tensor[:][1][:][:]
rank_4_tensor[:,1]


<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [351]:
rank_4_tensor[:][:][:][:]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [341]:
rank_4_tensor[1,:]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

##### Size
- Meaning: The total number of items in the tensor.
- Code: tf.size(tensor)

In [334]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

##### Attributes

In [358]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor (showing using numpy conversion):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor (showing using numpy conversion): 120


## Video 21: Indexing and Expanding tensors

### Indexing Tensors

Tensors can be indexed just like python lists.

In [363]:
# Python list indexing
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [364]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [365]:
some_list[:1]

[1]

In [ ]:
# Get the first element from each dimension from each index except for the final one

